package bst;

import bst.StringBST;
import bst.Node;
import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.font.TextLayout;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * @author Faber Fred
 */
public class StringBSTView extends javax.swing.JPanel implements PropertyChangeListener {

    private StringBST tree = null;

    public void setTree(StringBST tree) {
        this.tree = tree;
    }
    
    /**
     * Creates new form StringBSTView
     */
    public StringBSTView() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if  (tree!=null) 
            draw(g, getWidth(), getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    
 //************************* Observers et Observable ********************************
    
    //méthode addObserver appelée dans MainFrame
    
    //Méthode appelée automatiquement lors d'un changement dans la classe observée
    public void propertyChange(PropertyChangeEvent arg0) {
        repaint(); //s'actualiser
    }
    
    
    
 //************************** AFFICHAGE GRAPHIQUE ***********************************

private Color BGColor     = new Color (0xBB, 0xEE, 0xFF);
private Color FontColor   = new Color (0x00, 0x00, 0xFF);
private Color BorderColor = new Color (0x00, 0x00, 0x99);
    
public void draw(Graphics gr, int w, int h) {
    Graphics2D g = (Graphics2D)gr;
    //turn antialiasing on
    g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);    
    //set Font for representation (can be changed - all sizes adapt automatically)
    int fontSize = 14;
    g.setFont(new Font("Arial", Font.BOLD, fontSize));
   
    //distance between different levels
    int step;
    if (tree.getDepth()>0) step = Math.max(40, h/(tree.getDepth()));
    else step=40;
    
    //draw tree info (position: bottom left)
    g.setColor(FontColor);
    g.drawString("Tree size: " +tree.size(),     10, h-fontSize-10);
    g.drawString("Tree depth: "+tree.getDepth(), 10, h-5);
    
    //draw the tree
    drawRecursion (tree.getRoot(), g, w/2, 5, w/2, step);
}
    
    
//Draws a string inside a bordered rectangle and returns the bounds
private Rectangle2D drawBorderedString(Graphics2D g, String s, Point p) {
   Point2D loc = p;
   
   FontRenderContext frc = g.getFontRenderContext();
   TextLayout layout = new TextLayout( s , g.getFont(), frc);
   
   //layout.draw(g, (float)loc.getX(), (float)loc.getY());

   Rectangle2D bounds = layout.getBounds();
   bounds.setRect((int)(bounds.getX()-bounds.getWidth()/2+loc.getX()-4),
                  (int)(bounds.getY()+bounds.getHeight() +loc.getY()),
                  (int)(bounds.getWidth ()+6),
                  (int)(bounds.getHeight()+7));
   
   g.setColor(Color.WHITE);
   g.fill(bounds);
   g.setColor(BorderColor);
   g.draw(bounds);
   g.setColor(FontColor);
   g.drawString(s, p.x-(int)bounds.getWidth()/2+1, p.y+(int)bounds.getHeight()-2);
   return bounds;
}

    
private void drawRecursion (Node node, Graphics2D g, int x, int y, int dist, int step) {
   double length,top,width,height;
   
   if (node==null) drawBorderedString( g, "null", new Point(x-1, y));
   else {
           //draw data string with rectangle
           Rectangle2D bounds =
                   drawBorderedString( g, node.data, new Point(x-1, y));

           //use returned bounds for the 2 lower rectangles
           length = bounds.getX();
           top    = bounds.getY();
           height = bounds.getHeight();
           width  = bounds.getWidth();
   
           dist = dist / 2; //
           g.setColor(Color.WHITE);
           g.fillRect((int)length, (int)(top+height), (int)(width),  11);
           
           g.setColor(BorderColor);
           g.drawRect((int)length, (int)(top+height), (int)(width/2),  11);
           //left bullet
           g.setColor(BGColor);
           g.fillOval((int)(length+width/4-3), (int)(top+height+3) , 5, 5);
           g.setColor(BorderColor);
           g.drawOval((int)(length+width/4-3), (int)(top+height+3) , 5, 5);
           //left pointer
           if (node.left!=null) {
              g.drawLine((int)(length+width/4), (int)(top+height+6), (int)(x-dist-2), (int)(y+step));
              drawRecursion (node.left, g, x-dist, y+step, dist, step);
           }

           g.setColor(BorderColor);
           g.drawRect((int)length, (int)(top+height), (int)width, 11);
           //right bullet
           g.setColor(BGColor);
           g.fillOval((int)(length+3*width/4-2), (int)(top+height+3), 5, 5);
           g.setColor(BorderColor);
           g.drawOval((int)(length+3*width/4-2), (int)(top+height+3), 5, 5);
           //right pointer
           if (node.right!=null)  {
                g.drawLine((int)(length+3*width/4+1), (int)(top+height+6), (int)(x+dist-2), (int)(y+step));
                drawRecursion (node.right, g, x+dist, y+step, dist, step);
           }
     }
        
 }


}
