import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import java.io.File;
import java.io.IOException;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawFrame.java
 *
 * Created on Dec 20, 2010, 5:17:58 PM
 */

/**
 *
 * @author fred
 */
public class DrawFrame extends javax.swing.JFrame {

    //Dossier par défaut -> dossier du projet (voir cours...)
    protected String currentFile = System.getProperty("user.dir");

    
    //********* self-defined FileFilter ********** (plus nécessaire pour Java > 5) ****
    protected FileFilter drwFilter=new FileFilter() {

            @Override
            public String getDescription() {
              return "Draw Files (.drw)";
            }

            @Override
            public boolean accept(File f) {
              String s=f.getName();
              return f.isDirectory() || s.substring(s.length()-3).toLowerCase().equals("drw");
            }
    };   

    
    protected FileFilter txtFilter=new FileFilter() {

            @Override
            public String getDescription() {
              return "Text Files (.txt)";
            }

            @Override
            public boolean accept(File f) {
              String s=f.getName();
              return f.isDirectory() || s.substring(s.length()-3).toLowerCase().equals("txt");
            }
    };
    //**********************************************************************************

    
    /** Creates new form DrawFrame */
    public DrawFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drawModeList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionModeList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonNew = new javax.swing.JButton();
        buttonLoad = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        borderColorButton = new javax.swing.JButton();
        fillColorButton = new javax.swing.JButton();
        drawPanel = new DrawPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawModeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Rectangle", "Ellipse", "Line" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        drawModeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        drawModeList.setSelectedIndex(0);
        drawModeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                drawModeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(drawModeList);

        actionModeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Draw", "Delete", "Forward", "Backward", "To Top", "To Bottom", "Move" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        actionModeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        actionModeList.setSelectedIndex(0);
        actionModeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                actionModeListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(actionModeList);

        jLabel1.setText("Draw Mode :");

        jLabel2.setText("Action Mode :");

        buttonNew.setText("New");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonLoad.setText("Load ...");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        buttonSave.setText("Save ...");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        borderColorButton.setText("Border Color ...");
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonActionPerformed(evt);
            }
        });

        fillColorButton.setText("Fill Color ...");
        fillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fillColorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(borderColorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(buttonNew)
                                .addComponent(buttonLoad))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borderColorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillColorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSave)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        drawPanel.setBackground(new java.awt.Color(255, 255, 204));
        drawPanel.setForeground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionModeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_actionModeListValueChanged
        drawPanel.setActionMode(actionModeList.getSelectedIndex());
    }//GEN-LAST:event_actionModeListValueChanged

    private void drawModeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_drawModeListValueChanged
        drawPanel.setDrawMode(drawModeList.getSelectedIndex());
    }//GEN-LAST:event_drawModeListValueChanged

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        drawPanel.clear();
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed

        // Show the dialog; this method does not return until the dialog is closed
        JFileChooser fc = new JFileChooser(currentFile);
        //fc.setAcceptAllFileFilterUsed(false);  //hides 'All Files' Filter
        //fc.addChoosableFileFilter(drwFilter);    //uses my self defined FileFilter
        //fc.addChoosableFileFilter(txtFilter);    //uses my self defined FileFilter
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Draw files (*.drw)","drw"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Text files (*.txt)","txt"));

        if (fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION) {
             currentFile = fc.getSelectedFile().getName();
             //version deluxe:
             //pour détecter à partir de l'extension, si l'utilisateur veut sauver comme texte ou comme objet
             if (txtFilter.accept(fc.getSelectedFile()))  
                {
                 try
                   { drawPanel.loadFromTxtFile(currentFile);  }
                 catch (IOException e)
                   { System.out.println("IOError opening file : "+currentFile); }
                 }
             else if (drwFilter.accept(fc.getSelectedFile()))
                   drawPanel.loadFromFile(currentFile);
             else System.out.println("Error opening file : "+currentFile +" - Wrong Filter selected");
        }
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
 
        // Show the dialog; this method does not return until the dialog is closed
        JFileChooser fc = new JFileChooser(currentFile);
        //fc.setAcceptAllFileFilterUsed(false);  //hides 'All Files' Filter
        //fc.addChoosableFileFilter(drwFilter);    //uses my self defined FileFilter
        //fc.addChoosableFileFilter(txtFilter);    //uses my self defined FileFilter
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Draw files (*.drw)","drw"));
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Text files (*.txt)","txt"));

        if (fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
             currentFile = fc.getSelectedFile().getName();
             
             //version deluxe:
             //pour détecter à partir de l'extension, si l'utilisateur veut sauver comme texte ou comme objet
             if (txtFilter.accept(fc.getSelectedFile())) //pour détecter, si l'utilisateur veut sauver comme texte ou comme objet
                {
                 try
                   { drawPanel.saveToTxtFile(currentFile);  }
                 catch (IOException e)
                     { System.out.println("IOError saving file : "+currentFile); }
                 }
             else if(drwFilter.accept(fc.getSelectedFile()))
                   drawPanel.saveToFile(currentFile);
             else System.out.println("Error saving file : "+currentFile +" - Wrong Filter selected");

        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void borderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonActionPerformed
        // init dialog with current color
        Color initialColor = drawPanel.getBorderColor();
        // Show the dialog; this method does not return until the dialog is closed
        Color newColor = JColorChooser.showDialog(this, "Choose Border Color", initialColor);
        drawPanel.setBorderColor(newColor);
    }//GEN-LAST:event_borderColorButtonActionPerformed

    private void fillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorButtonActionPerformed
        // init dialog with current color
        Color initialColor = drawPanel.getFillColor();
        // Show the dialog; this method does not return until the dialog is closed
        Color newColor = JColorChooser.showDialog(this, "Choose Fill Color", initialColor);
        drawPanel.setFillColor(newColor);
    }//GEN-LAST:event_fillColorButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList actionModeList;
    private javax.swing.JButton borderColorButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JList drawModeList;
    private DrawPanel drawPanel;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
