/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import java.awt.Color;
import java.awt.Graphics;
import logic.*;

/**
 *
 * @author kas
 */
public class DrawPanel extends javax.swing.JPanel {

    private Targets t = null;
    private HighScores highScores = null;
    private int score = 0;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
        highScores = new HighScores();
    }

    public void setT(Targets t) {
        this.t = t;
    }

    public void saveScore(int score) {
        highScores.add(score);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (t != null) {
            t.draw(g);
        } else {
            g.setColor(Color.BLUE);
            g.drawString("GAME OVER", getWidth() / 2 - 50, 15);
            highScores.draw(g, getWidth() / 2 - 50, 100);
            highScores.save();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
