/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphics;

import java.awt.Color;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import logic.*;
import logic.Dot;
import logic.Grid;

/**
 *
 * @author yvonschubert
 */
public class GridView extends javax.swing.JPanel {

    Grid myGrid = new Grid(10, 15);
     //Gets the current file path
    private String currentFileName = System.getProperty("user.dir"); // ou "."; 

    /**
     * Creates new form GridView
     */
    public GridView() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        int w = getWidth();
        int h = getHeight();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);
        myGrid.draw(g, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        int randomColor = (int) (Math.random() * 4);
        Color c = Color.BLACK;
        switch (randomColor) {
            case 0:
                c = Color.BLUE;
                break;
            case 1:
                c = Color.RED;
                break;
            case 2:
                c = Color.YELLOW;
                break;
            case 3:
                c = Color.GREEN;
                break;
        }
        int x = evt.getX();
        int y = evt.getY();
        int cellWidth = myGrid.getCellWidth();

        Dot myDot = new Dot(x / cellWidth, y / cellWidth, c);
        myGrid.addDot(myDot);
        repaint();
    }//GEN-LAST:event_formMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == 'n') { //new (clear) grid
            myGrid.clear();
            repaint();
        }

        if (evt.getKeyChar() == 's') { //save grid in a file
            JFileChooser jfc = new JFileChooser(currentFileName);
            FileFilter ff = new FileNameExtensionFilter(
                    "Dots text Files (*.txt)", "txt");
            //Adds a filter to the list of user choosable file filters
            jfc.addChoosableFileFilter(ff);
            //Sets the file view to used to retrieve UI information, such as the icon that represents a file or the type description of a file.
            jfc.setFileFilter(ff);
            //Determines whether the AcceptAll FileFilter is used as an available choice in the choosable filter list.
            //If false, the AcceptAll file filter is removed from the list of available file filters. 
            jfc.setAcceptAllFileFilterUsed(false);
            
            //Pops up an "Open File" file chooser dialog.
            //JFileChooser.APPROVE_OPTION ->Return value if approve (yes, ok) is chosen.
            if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                try {
                    //get the absolut path of the file
                    String fileName = jfc.getSelectedFile().getAbsolutePath();
                    //Tests the specified file, returning true if the file is accepted, false otherwise. 
                    //Accepted means extension matches one of the file name extensions of this FileFilter, or the file is a directory.
                    if(!ff.accept(jfc.getSelectedFile()))
                    {
                        fileName+=".txt";
                    }
                    myGrid.saveToTxtFile(fileName);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
            }
            JOptionPane.showMessageDialog(this, "file saved.");
        }

        if (evt.getKeyChar() == 'l') {
            JFileChooser jfc = new JFileChooser(currentFileName);
            FileFilter ff = new FileNameExtensionFilter(
                    "Dots text Files (*.txt)", "txt");
            jfc.addChoosableFileFilter(ff);
            jfc.setFileFilter(ff);
            jfc.setAcceptAllFileFilterUsed(false);
            if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                try {
                    //load grid from file
                    String fileName = jfc.getSelectedFile().getAbsolutePath();
                    myGrid.loadFromTxtFile(fileName);
                    currentFileName = fileName;  //seulement si succès
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
            }
            repaint();
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
