
import java.awt.Color;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yvonschubert
 */
public class MainFrame extends javax.swing.JFrame {
    private ShapeList alShape = new ShapeList();
    private int countMyButtons=2;
    private int countMyTextFields=2;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Triangle  t = new Triangle (100,100, java.awt.Color.red , 40,50,30); 
        Rectangle r = new Rectangle(200,200, java.awt.Color.blue, 50,60); 
        Circle    c = new Circle   (300,300, java.awt.Color.pink, 10);
        Square    s = new Square   (400,400, java.awt.Color.cyan, 25);
        MyButton b1= new MyButton(6, 53, 89, 27, "myButton1");
        MyButton b2= new MyButton(6, 6, 169, 41, "myButton2");
        MyTextField t1= new MyTextField(6, 86, 169, 27, "MyTextField1");
        MyTextField t2= new MyTextField(6, 125, 91, 69, "MyTextField2");
        
        myComponentsPanel.add(b1);
        myComponentsPanel.add(b2);
        myComponentsPanel.add(t1);
        myComponentsPanel.add(t2);
        
        alShape.add(t);
        alShape.add(r);
        alShape.add(s);
        alShape.add(c);
        alShape.add(b1);
        alShape.add(b2);
        alShape.add(t1);
        alShape.add(t2);
        updateView();
    }
    
    public void updateView()
    {
        shapeList.setListData(alShape.toArray());
    }
    
    public int getRandom(int min, int max)
    {
        return (int) (Math.random()*(max-min+1))+min;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        shapeList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        addShapeButton = new javax.swing.JButton();
        addComponentButton = new javax.swing.JButton();
        sortButton = new javax.swing.JButton();
        myComponentsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shapeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(shapeList);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        addShapeButton.setText("Add Shapes");
        addShapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShapeButtonActionPerformed(evt);
            }
        });

        addComponentButton.setText("Add 'my' Components");
        addComponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComponentButtonActionPerformed(evt);
            }
        });

        sortButton.setText("Sort");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortButton)
                    .addComponent(addComponentButton)
                    .addComponent(addShapeButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addShapeButton)
                .addGap(18, 18, 18)
                .addComponent(addComponentButton)
                .addGap(18, 18, 18)
                .addComponent(sortButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        myComponentsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout myComponentsPanelLayout = new javax.swing.GroupLayout(myComponentsPanel);
        myComponentsPanel.setLayout(myComponentsPanelLayout);
        myComponentsPanelLayout.setHorizontalGroup(
            myComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myComponentsPanelLayout.setVerticalGroup(
            myComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myComponentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(myComponentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addShapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShapeButtonActionPerformed
        int x=getRandom(100, 1000);
        int y=getRandom(100, 1000);
        Color c= new Color(getRandom(0, 255), getRandom(0, 255), getRandom(0, 255));
        int shape=getRandom(0, 3);
        switch (shape) {
            case 0: alShape.add(new Circle(x, y, c, getRandom(100, 1000)));break;
            case 1: alShape.add(new Triangle(x, y, c, getRandom(100, 1000), getRandom(100, 1000), getRandom(100, 1000)));break;
            case 2: alShape.add(new Rectangle(x, y, c, getRandom(100, 1000), getRandom(100, 1000)));break;
            case 3: alShape.add(new Square(x, y, c, getRandom(100, 1000)));break;
        }
        updateView();
    }//GEN-LAST:event_addShapeButtonActionPerformed

    private void addComponentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComponentButtonActionPerformed
       //int component=getRandom(0, 1);
       int component=1;
       if(component==0) {
           MyButton myBtn= new MyButton(6, myComponentsPanel.getWidth()/(countMyButtons+countMyTextFields+1), getRandom(10, myComponentsPanel.getWidth()), getRandom(10, myComponentsPanel.getHeight()), "myButton"+ ++countMyButtons);
           myComponentsPanel.add(myBtn);
           alShape.add(myBtn);
        }
       else
       {
           MyTextField myTxtField= new MyTextField(6, myComponentsPanel.getWidth()/(countMyButtons+countMyTextFields+1), getRandom(10, myComponentsPanel.getWidth()), getRandom(10, myComponentsPanel.getHeight()), "myTextField"+ ++countMyTextFields);
           myComponentsPanel.add(myTxtField);
           alShape.add(myTxtField);
       }
       updateView();
    }//GEN-LAST:event_addComponentButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        alShape.sort();
        updateView();
    }//GEN-LAST:event_sortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComponentButton;
    private javax.swing.JButton addShapeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel myComponentsPanel;
    private javax.swing.JList shapeList;
    private javax.swing.JButton sortButton;
    // End of variables declaration//GEN-END:variables
}
