package gui;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import logic.BlockMap;
import gui.MainFrame;
import java.awt.Graphics;

/**
 *
 * @author timlo
 */
public class DrawPanel extends javax.swing.JPanel {
    private int size = 40;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();

        MainFrame.map = new BlockMap(0, 0);
    }

    public void paintComponent(Graphics g) {
        if (MainFrame.map.getDim() == 0) {
            MainFrame.map = new BlockMap(Math.min(getWidth(), getHeight()) / size, size);
        } else {
            MainFrame.map.setDim(Math.min(getWidth(), getHeight()) / size);
        }

        super.paintComponent(g);

        MainFrame.map.draw(g, getWidth(), getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
