
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.Timer;

/**
 * Class name:   DrawPanel								//13p
 * @version Sep 15, 2012
 * @author  fred
 */
public class DrawPanel extends javax.swing.JPanel {

    private TargetList tl; 
    private HighScores highScores = new HighScores();
    
    Timer timer;
    private int score;
    
    private final static int GAME_DURATION=30;
    Timer timeOutTimer;
    private int timeOut;

    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();			
        
        score=0;
        timeOut=GAME_DURATION; 
        
        stepButton.setVisible(false); 
        timeOutButton.setVisible(false);         
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);					
        
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        
        g.setFont(g.getFont().deriveFont(Font.BOLD, (float)16.0));
        g.setColor(Color.RED);
        g.drawString("Score: "  +score   , 5, 15);

        if (tl!=null) 
        {
            g.setColor(Color.RED);
            g.drawString("Timeout: "+timeOut , getWidth()-100, 15);
            tl.draw(g);
        }           
        else
        {
            g.setColor(Color.BLUE);
            g.drawString("GAME OVER"   , getWidth()/2-50, 15);
            highScores.draw(g, getWidth()/2-50, 100);
        }        
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stepButton = new javax.swing.JButton();
        timeOutButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        stepButton.setText("step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        timeOutButton.setText("timeOut");
        timeOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOutButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(timeOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepButton)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepButton)
                    .addComponent(timeOutButton)
                    .addComponent(startButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        tl.doStep(getWidth(), getHeight());					
        repaint();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        score += tl.shoot(evt.getX(), evt.getY());			
        repaint();  
    }//GEN-LAST:event_formMousePressed

    private void timeOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOutButtonActionPerformed
        timeOut--;
        if (timeOut==0) {
            //stop game
            timer.stop();
            timeOutTimer.stop();
            
            startButton.setVisible(true);  
            
            tl=null;
            repaint();            
            highScores.add(score);
            repaint();   
        } 
    }//GEN-LAST:event_timeOutButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        score   = 0;
        timeOut = GAME_DURATION; 
        tl= new TargetList();
        
        
        timer = new Timer(50, stepButton.getActionListeners()[0]);
        timer.start();   
        
        timeOutTimer = new Timer(1000, timeOutButton.getActionListeners()[0]);
        timeOutTimer.start(); 
        
        startButton.setVisible(false);             
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startButton;
    private javax.swing.JButton stepButton;
    private javax.swing.JButton timeOutButton;
    // End of variables declaration//GEN-END:variables

    public void saveHiScores() {
        highScores.save();
    }

}