package gui;


import wordlists.UnknownWord;
import wordlists.UnknownWordList;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import spellcheckers.*;
import java.io.IOException;
import java.net.URL;
import java.net.URLDecoder;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import wordlists.PersonalDictionary;

/**
 * Class name:   MainFrame
 * @version Feb 11, 2014
 * @author  fred
 */
public class MainFrame extends javax.swing.JFrame {
    
    private Spellchecker spellchecker = null;
    private UnknownWordList unknownWords = null;
    private PersonalDictionary dictionary = new PersonalDictionary();
    
    public static final String WORD_FILE           = "../dict/DE_Wortliste_UTF8.txt";
    public static final String PERSONAL_DICTIONARY = "./src/dict/PersonalDictionary.txt";

    private void selectSpellchecker() {
        if (arrayListRadioButton.isSelected()) 
            spellchecker = new SpellcheckerArrayList();
        else if (linkedListRadioButton.isSelected()) 
            spellchecker = new SpellcheckerLinkedList();
        else if (treeSetRadioButton.isSelected()) 
            spellchecker = new SpellcheckerTreeSet();
        else 
            spellchecker = new SpellcheckerBST();
        try {
            //spellchecker.loadFromFile("DE_Wortliste_UTF8.txt");
            URL myurl = this.getClass().getResource (WORD_FILE);
            spellchecker.loadFromFile(URLDecoder.decode(myurl.getFile(), "UTF-8"));
            if ((new File(PERSONAL_DICTIONARY)).exists()) {
                spellchecker.loadFromFile(PERSONAL_DICTIONARY);
                dictionary.loadFromFile(PERSONAL_DICTIONARY);
            }
        } catch (IOException  ex) {
            System.err.println(ex);
        }
    }
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        selectSpellchecker();
    }

    /** This method is called from within the constructor to initialize the form
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        checkButton = new javax.swing.JButton();
        loadFileButton = new javax.swing.JButton();
        arrayListRadioButton = new javax.swing.JRadioButton();
        linkedListRadioButton = new javax.swing.JRadioButton();
        treeSetRadioButton = new javax.swing.JRadioButton();
        BSTRadioButton = new javax.swing.JRadioButton();
        checkTimeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        unknownWordList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("Aber dies ist ein einfacher Text, der absolut kainen Fehler enthällt. Jeder Satz beginnt mit einem Grossbuchstaben. Ich hoffee, die werden nicht alle als Fehler markiert.");
        jScrollPane1.setViewportView(textArea);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        loadFileButton.setText("Load Text File...");
        loadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(arrayListRadioButton);
        arrayListRadioButton.setText("ArrayList");
        arrayListRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrayListRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(linkedListRadioButton);
        linkedListRadioButton.setText("LinkedList");
        linkedListRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedListRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(treeSetRadioButton);
        treeSetRadioButton.setSelected(true);
        treeSetRadioButton.setText("TreeSet");
        treeSetRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeSetRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(BSTRadioButton);
        BSTRadioButton.setText("BST");
        BSTRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSTRadioButtonActionPerformed(evt);
            }
        });

        checkTimeLabel.setText("-");

        jLabel2.setText("Running Time: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadFileButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkButton)
                    .addComponent(checkTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSTRadioButton)
                    .addComponent(treeSetRadioButton)
                    .addComponent(arrayListRadioButton)
                    .addComponent(linkedListRadioButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkButton)
                            .addComponent(loadFileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkTimeLabel)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(arrayListRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkedListRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treeSetRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BSTRadioButton))
        );

        unknownWordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unknownWordListMouseClicked(evt);
            }
        });
        unknownWordList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                unknownWordListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(unknownWordList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        //startTime 
        long start = System.nanoTime();
        unknownWords = spellchecker.analyseText(textArea.getText());
        //unknownWords = spellchecker.analyseText_Simple(textArea.getText());
        //endTime
        long end = System.nanoTime();
        checkTimeLabel.setText((end-start)/1000000.0+" ms");
        //--> output checking time
        unknownWordList.setListData(unknownWords.toArray());
    }//GEN-LAST:event_checkButtonActionPerformed

    private void unknownWordListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_unknownWordListValueChanged
        int index = unknownWordList.getSelectedIndex();
        if (index > -1) {
            UnknownWord unknownWord = unknownWords.get(index);
            if (unknownWord != null) {
                textArea.setSelectionColor(Color.YELLOW);
                textArea.requestFocus();                
                textArea.setSelectionStart(unknownWord.getIndex());
                textArea.setSelectionEnd(unknownWord.getIndex() + unknownWord.getWord().length());
            }
        }
    }//GEN-LAST:event_unknownWordListValueChanged

    private void arrayListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrayListRadioButtonActionPerformed
        selectSpellchecker();
    }//GEN-LAST:event_arrayListRadioButtonActionPerformed

    private void linkedListRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedListRadioButtonActionPerformed
        selectSpellchecker();
    }//GEN-LAST:event_linkedListRadioButtonActionPerformed

    private void treeSetRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeSetRadioButtonActionPerformed
        selectSpellchecker();
    }//GEN-LAST:event_treeSetRadioButtonActionPerformed

    private void BSTRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSTRadioButtonActionPerformed
        selectSpellchecker();
    }//GEN-LAST:event_BSTRadioButtonActionPerformed

    
    private String currentFile = "./.";
    
    //too slow for large files...
    private String loadTextFile(String fileName) throws FileNotFoundException, IOException {
        String result="";
        try(BufferedReader in = new BufferedReader(new FileReader(fileName))) {
            String line;
            while((line = in.readLine()) != null) {
                result += line+System.getProperty("line.separator");
            }                
        }
        return result;
    }
    
    //trickier but quicker!
    private String loadTextFile(String fileName, Charset encoding) throws IOException {
        byte[] encoded = Files.readAllBytes(Paths.get(fileName));
        return encoding.decode(ByteBuffer.wrap(encoded)).toString();
    }

    
    private void loadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileButtonActionPerformed
        // Show the dialog; this method does not return until the dialog is closed
        JFileChooser fc = new JFileChooser(currentFile);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Text files (*.txt)", "txt"));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                currentFile = fc.getSelectedFile().getCanonicalPath();
            
                //textArea.setText(loadTextFile(currentFile)); //slow!
                textArea.setText(loadTextFile(currentFile, Charset.defaultCharset())); //Platform default charset
                //textArea.setText(loadTextFile(currentFile, StandardCharsets.UTF_8));
                //textArea.setText(loadTextFile(currentFile, StandardCharsets.ISO_8859_1));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loadFileButtonActionPerformed

    //add words form unknown word list to spellchecker and personal dictionary (by double clicking)
    private void unknownWordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unknownWordListMouseClicked
        if(evt.getClickCount()==2) { 
            int i = unknownWordList.getSelectedIndex();
            if(i>-1) {
                String word = unknownWords.get(i).getWord();
                spellchecker.add(word);
                dictionary.add(word);
                unknownWords.removeAll(word); 
                unknownWordList.setListData(unknownWords.toArray());
            }       
        }
    }//GEN-LAST:event_unknownWordListMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (dictionary.isChanged())
            try {
                dictionary.saveToFile(PERSONAL_DICTIONARY);
        } catch (IOException ex) {
                System.err.println("Error while saving private dictionary - "+ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BSTRadioButton;
    private javax.swing.JRadioButton arrayListRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel checkTimeLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton linkedListRadioButton;
    private javax.swing.JButton loadFileButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JRadioButton treeSetRadioButton;
    private javax.swing.JList unknownWordList;
    // End of variables declaration//GEN-END:variables

}
