
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.Timer;

/**
 * Class name:   DrawPanel								//13p
 * @version Sep 15, 2012
 * @author  fred
 */
public class DrawPanel extends javax.swing.JPanel {

    private TargetList tl = new TargetList();  //1p
    private int score;

    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();			//4p        
        
        score=0;
        
        stepButton.setVisible(false);
        Timer timer = new Timer(50, stepButton.getActionListeners()[0]);
        timer.start();        
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);					//4p
        
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.RED);
        g.drawRect(0, 0, getWidth()-1, getHeight()-1);
        
        tl.draw(g);
        
        g.setColor(Color.RED);
        g.drawString("Score: "+score, 5, 15);
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stepButton = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        stepButton.setText("step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(stepButton)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(stepButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        tl.doStep(getWidth(), getHeight());					//2p
        repaint();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        score += tl.shoot(evt.getX(), evt.getY());			//2p
        repaint();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables

}