/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graphics;

import java.awt.Color;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logic.*;
import logic.Dot;
import logic.Grid;

/**
 *
 * @author yvonschubert
 */
public class GridView extends javax.swing.JPanel {

    private Grid myGrid;

    /**
     * Creates new form GridView
     */
    public GridView() {
        initComponents();
        repaint();
    }

    public void setGrid(Grid pGrid) {
        myGrid = pGrid;
    }

    public void paintComponent(Graphics g) {
        int w = getWidth();
        int h = getHeight();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);
        if(myGrid!=null)
        {
        myGrid.draw(g, w, h);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(400, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        int randomColor = (int) (Math.random() * 4);
        Color c = Color.BLACK;
        switch (randomColor) {
            case 0:
                c = Color.BLUE;
                break;
            case 1:
                c = Color.RED;
                break;
            case 2:
                c = Color.YELLOW;
                break;
            case 3:
                c = Color.GREEN;
                break;
        }
        int x = evt.getX();
        int y = evt.getY();
        int cellWidth = myGrid.getCellWidth();

        Dot myDot = new Dot(x / cellWidth, y / cellWidth, c);
        myGrid.addDot(myDot);
        repaint();
    }//GEN-LAST:event_formMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == 'n') { //new (clear) grid
            myGrid.clear();
            repaint();
        }

        if (evt.getKeyChar() == 's') { //save grid in a file
            try {
                myGrid.saveToTxtFile("dots.txt");
                //myGrid.saveToBinaryFile("dots.txt");
                //myGrid.saveToXmlDom("dots.csv");
                //myGrid.saveToBinaryObject("dots.txt");
            } catch (IOException ex) {
                Logger.getLogger(GridView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "file saved as \"dots.txt\" ...");
        }

        if (evt.getKeyChar() == 'l') {
            try {
                //load grid from file
                //myGrid.loadFromXmlDom("dots.csv");
                myGrid.loadFromTxtFile("dots.txt");
                //myGrid.loadFromBinaryFile("dots.txt"); 
                //myGrid.loadFromBinaryObject("dots.txt");
            } catch (IOException ex) {
                Logger.getLogger(GridView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        repaint();

    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
