
import java.awt.Graphics;

/**
 * Class name:   DrawPanel
 * @version Dec 15, 2014
 * @author  fred
 */
public class DrawPanel extends javax.swing.JPanel {

    private Hanoi hanoi;

    public Hanoi getHanoi() {
        return hanoi;
    }

    public void setHanoi(Hanoi hanoi) {
        this.hanoi = hanoi;
    }
    
    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        if(hanoi!=null) {
            g.setColor(getBackground());
            g.fillRect(0, 0, getWidth(), getHeight());
            hanoi.draw(g, getWidth(), getHeight());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
