import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * @author FabFr297
 */
public class MainFrame extends javax.swing.JFrame {
    private Hanoi hanoi = null;    
    private Timer showMovesTimer = null;
    
    private void updateView() {
        boolean isRunning = showMovesTimer.isRunning();
        stopButton.setEnabled(isRunning); 
        calculateMovesjButton.setEnabled(!isRunning); 
        showMovesButton.setEnabled(!isRunning && hanoi.getCurrentMove()==0);
        continueButton.setEnabled (!isRunning && hanoi.getCurrentMove()!=0 && 
                                  hanoi.getCurrentMove()<hanoi.numberOfMoves()); 
        repaint();        
    }
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
         
        showMovesTimer = new Timer (speedSlider.getValue(), new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                boolean goOn = hanoi.makeNextMove();
                if (!goOn) {
                    showMovesTimer.stop(); 
                    updateView();
                    //wait for previous timer-operations to finish 
                    //necessary if timer interval is too short for drawing operations
                    // --> mainly in turbo mode
                    try {
                        Thread.currentThread().sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    repaint();
                }                
                else 
                    if (speedSlider.getValue()!=0) {
                        movesList.setSelectedIndex(hanoi.getCurrentMove());  
                        movesList.ensureIndexIsVisible(hanoi.getCurrentMove());
                        currentMoveLabel.setText(hanoi.getCurrentMove()+"/"+hanoi.numberOfMoves());
                    }
                    else { //if speed is at maximum :
                        //-> turbo mode: do not scroll list
                        currentMoveLabel.setText(hanoi.getCurrentMove()+"/"+hanoi.numberOfMoves());
                        movesList.clearSelection();                    
                    }
                drawPanel1.repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movesList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        numberOfDisksTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        calculateMovesjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numberOfMovesLabel = new javax.swing.JLabel();
        drawPanel1 = new DrawPanel();
        showMovesButton = new javax.swing.JButton();
        currentMoveLabel = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Towers of Hanoï");

        jScrollPane1.setViewportView(movesList);

        jLabel1.setText("Number of Disks: ");

        numberOfDisksTextField.setText("10");

        jLabel2.setText("from :");

        jLabel3.setText("to :");

        fromTextField.setText("1");

        toTextField.setText("3");

        calculateMovesjButton.setText("Calculate Moves");
        calculateMovesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMovesjButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Number of Moves: ");

        numberOfMovesLabel.setText("-");

        drawPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        showMovesButton.setText("Show Moves");
        showMovesButton.setEnabled(false);
        showMovesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMovesButtonActionPerformed(evt);
            }
        });

        currentMoveLabel.setText("-");

        stopButton.setText("stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        continueButton.setText("continue");
        continueButton.setEnabled(false);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        speedSlider.setMajorTickSpacing(20);
        speedSlider.setMaximum(200);
        speedSlider.setMinorTickSpacing(2);
        speedSlider.setPaintLabels(true);
        speedSlider.setPaintTicks(true);
        speedSlider.setValue(80);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });

        jLabel5.setText("Delay :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(fromTextField))
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(toTextField))
                                        .addComponent(numberOfDisksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(calculateMovesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfMovesLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(currentMoveLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showMovesButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stopButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(continueButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfDisksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateMovesjButton)
                    .addComponent(showMovesButton)
                    .addComponent(stopButton)
                    .addComponent(continueButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberOfMovesLabel)
                    .addComponent(currentMoveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateMovesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMovesjButtonActionPerformed
       try {
            hanoi = new Hanoi(Integer.valueOf(numberOfDisksTextField.getText()), 
                              Integer.valueOf(fromTextField.getText()), 
                              Integer.valueOf(toTextField.getText()));
            drawPanel1.setHanoi(hanoi);
            hanoi.calculateMoves();
            movesList.setListData(hanoi.toArray());
            numberOfMovesLabel.setText(String.valueOf(hanoi.numberOfMoves()));
            currentMoveLabel.setText(hanoi.getCurrentMove()+"/"+hanoi.numberOfMoves());
            updateView();
       }
       catch (IllegalArgumentException exc) {
           JOptionPane.showMessageDialog(rootPane, exc.getMessage());
       }
    }//GEN-LAST:event_calculateMovesjButtonActionPerformed

    private void showMovesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMovesButtonActionPerformed
        showMovesTimer.start();        
        updateView();  
    }//GEN-LAST:event_showMovesButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        showMovesTimer.stop();
        updateView();        
    }//GEN-LAST:event_stopButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        showMovesTimer.start();        
        updateView();
        
    }//GEN-LAST:event_continueButtonActionPerformed

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        showMovesTimer.setDelay(speedSlider.getValue());
    }//GEN-LAST:event_speedSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateMovesjButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel currentMoveLabel;
    private DrawPanel drawPanel1;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList movesList;
    private javax.swing.JTextField numberOfDisksTextField;
    private javax.swing.JLabel numberOfMovesLabel;
    private javax.swing.JButton showMovesButton;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
