
import javax.swing.JFrame;

/**
 * @author FabFr297
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recuTab = new RecursiveTabVisual();
        jPanel1 = new javax.swing.JPanel();
        selectionSortButton = new javax.swing.JButton();
        quickSortButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numberOfValueTextField = new javax.swing.JTextField();
        fastForwardButton = new javax.swing.JButton();
        bubbleSortButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recuTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout recuTabLayout = new javax.swing.GroupLayout(recuTab);
        recuTab.setLayout(recuTabLayout);
        recuTabLayout.setHorizontalGroup(
            recuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        recuTabLayout.setVerticalGroup(
            recuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        selectionSortButton.setText("Selection Sort");
        selectionSortButton.setToolTipText("good old selection sort");
        selectionSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionSortButtonActionPerformed(evt);
            }
        });

        quickSortButton.setText("Quicksort");
        quickSortButton.setToolTipText("nomen est omen");
        quickSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSortButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of values : ");

        numberOfValueTextField.setText("50");
        numberOfValueTextField.setToolTipText("number of values to be sorted");

        fastForwardButton.setText(">>|");
        fastForwardButton.setToolTipText("don't show inner loops");
        fastForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastForwardButtonActionPerformed(evt);
            }
        });

        bubbleSortButton.setText("Bubble Sort");
        bubbleSortButton.setToolTipText("hello neighbor!");
        bubbleSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubbleSortButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bubbleSortButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionSortButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quickSortButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fastForwardButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectionSortButton)
                    .addComponent(quickSortButton)
                    .addComponent(fastForwardButton)
                    .addComponent(bubbleSortButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recuTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recuTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionSortButtonActionPerformed
        new Thread(new Runnable() { //to permit interrupting by MainFrame
            @Override
            public void run() {
                int n = Integer.valueOf( numberOfValueTextField.getText());
                recuTab.fill(n, 0, 1000);
                recuTab.selSort();
            }
        }).start(); 
    }//GEN-LAST:event_selectionSortButtonActionPerformed

    private void quickSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSortButtonActionPerformed
        new Thread(new Runnable() { //to permit interrupting by MainFrame
            @Override
            public void run() {
                int n = Integer.valueOf( numberOfValueTextField.getText());
                recuTab.fill(n, 0, 1000);
                recuTab.qs(0,n-1);
            }
        }).start(); 
    }//GEN-LAST:event_quickSortButtonActionPerformed

    private void fastForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastForwardButtonActionPerformed
        //don't show inner loops...
        recuTab.fastForward();
    }//GEN-LAST:event_fastForwardButtonActionPerformed

    private void bubbleSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubbleSortButtonActionPerformed
        new Thread(new Runnable() { //to permit interrupting by MainFrame
            @Override
            public void run() {
                int n = Integer.valueOf( numberOfValueTextField.getText());
                recuTab.fill(n, 0, 1000);
                recuTab.bubbleSort();
            }
        }).start(); 

    }//GEN-LAST:event_bubbleSortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainFrame f = new MainFrame();
                f.setVisible(true);
                //start maximized
                f.setExtendedState(f.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bubbleSortButton;
    private javax.swing.JButton fastForwardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberOfValueTextField;
    private javax.swing.JButton quickSortButton;
    private RecursiveTabVisual recuTab;
    private javax.swing.JButton selectionSortButton;
    // End of variables declaration//GEN-END:variables
}
